/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author arman
 */
public class vistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    
    public vistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel2 = new javax.swing.JLabel();
        jPCancelarFuncion = new javax.swing.JPanel();
        jBAtrasCancelarF_Main = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jBCancelarFuncionSeleccionada = new javax.swing.JButton();
        jPVentaBoletos = new javax.swing.JPanel();
        jBAtrasBoletos_Main = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jBComprarBoletos = new javax.swing.JButton();
        jBSeleccionarAsientosDeCompra = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPMenuPrincipal = new javax.swing.JPanel();
        jBVenderBoleto = new javax.swing.JButton();
        jBCancelarBoleto = new javax.swing.JButton();
        jBFunciones = new javax.swing.JButton();
        jBCrearFuncion = new javax.swing.JButton();
        jBCancelarFuncion = new javax.swing.JButton();
        jPFunciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBAtrasFunciones_Main = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPCancelarBoletos = new javax.swing.JPanel();
        jBAtrasCancelarB_Main = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jBCancelarBoletoAsiento = new javax.swing.JButton();
        jPCrearFuncion = new javax.swing.JPanel();
        jBCrearFuncion_Main = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jBAneadirFuncion = new javax.swing.JButton();
        jBAsientosDisponibles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Teatro Patito Feo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 16, -1, -1));

        jPCancelarFuncion.setVisible(false);
        jPCancelarFuncion.setMaximumSize(new java.awt.Dimension(610, 670));
        jPCancelarFuncion.setPreferredSize(new java.awt.Dimension(610, 670));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jBCancelarFuncion, org.jdesktop.beansbinding.ELProperty.create("${action}"), jPCancelarFuncion, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jBAtrasCancelarF_Main.setText("Atras");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setText("Lista de Funciones");

        jBCancelarFuncionSeleccionada.setText("Cancelar Funcion");
        jBCancelarFuncionSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarFuncionSeleccionadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCancelarFuncionLayout = new javax.swing.GroupLayout(jPCancelarFuncion);
        jPCancelarFuncion.setLayout(jPCancelarFuncionLayout);
        jPCancelarFuncionLayout.setHorizontalGroup(
            jPCancelarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCancelarFuncionLayout.createSequentialGroup()
                .addGroup(jPCancelarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCancelarFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBAtrasCancelarF_Main))
                    .addGroup(jPCancelarFuncionLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCancelarFuncionLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel3))
                    .addGroup(jPCancelarFuncionLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jBCancelarFuncionSeleccionada)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPCancelarFuncionLayout.setVerticalGroup(
            jPCancelarFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCancelarFuncionLayout.createSequentialGroup()
                .addGap(632, 632, 632)
                .addComponent(jBAtrasCancelarF_Main)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jBCancelarFuncionSeleccionada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPCancelarFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 610, 620));

        jPVentaBoletos.setVisible(false);
        jPVentaBoletos.setMinimumSize(new java.awt.Dimension(20, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jBVenderBoleto, org.jdesktop.beansbinding.ELProperty.create("${action}"), jPVentaBoletos, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jBAtrasBoletos_Main.setText("Atras");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel4.setText("Lista de Funciones");

        jLabel5.setText("Pelicula Seleccionada");

        jLabel6.setText("Numero de Boletos");

        jBComprarBoletos.setText("Comprar");

        jBSeleccionarAsientosDeCompra.setText("Seleccionar Asientos");

        javax.swing.GroupLayout jPVentaBoletosLayout = new javax.swing.GroupLayout(jPVentaBoletos);
        jPVentaBoletos.setLayout(jPVentaBoletosLayout);
        jPVentaBoletosLayout.setHorizontalGroup(
            jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVentaBoletosLayout.createSequentialGroup()
                .addGroup(jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVentaBoletosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBAtrasBoletos_Main))
                    .addGroup(jPVentaBoletosLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel4))
                    .addGroup(jPVentaBoletosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVentaBoletosLayout.createSequentialGroup()
                                .addGroup(jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBComprarBoletos)
                                    .addGroup(jPVentaBoletosLayout.createSequentialGroup()
                                        .addGroup(jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jBSeleccionarAsientosDeCompra))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4))))
                                .addGap(32, 32, 32)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPVentaBoletosLayout.setVerticalGroup(
            jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVentaBoletosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jBAtrasBoletos_Main)
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPVentaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSeleccionarAsientosDeCompra)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jBComprarBoletos)
                .addGap(62, 62, 62))
        );

        getContentPane().add(jPVentaBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 610, 670));

        jPMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPMenuPrincipal.setPreferredSize(new java.awt.Dimension(610, 670));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPMenuPrincipal, org.jdesktop.beansbinding.ELProperty.create("${background}"), jPMenuPrincipal, org.jdesktop.beansbinding.BeanProperty.create("foreground"));
        bindingGroup.addBinding(binding);

        jBVenderBoleto.setText("Vender Boletos");
        jBVenderBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVenderBoletoActionPerformed(evt);
            }
        });

        jBCancelarBoleto.setText("Cancelar Boletos");
        jBCancelarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarBoletoActionPerformed(evt);
            }
        });

        jBFunciones.setText("Funciones");
        jBFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFuncionesActionPerformed(evt);
            }
        });

        jBCrearFuncion.setText("Crear Funcion");
        jBCrearFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearFuncionActionPerformed(evt);
            }
        });

        jBCancelarFuncion.setText("Cancelar Funcion");
        jBCancelarFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarFuncionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMenuPrincipalLayout = new javax.swing.GroupLayout(jPMenuPrincipal);
        jPMenuPrincipal.setLayout(jPMenuPrincipalLayout);
        jPMenuPrincipalLayout.setHorizontalGroup(
            jPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuPrincipalLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jBVenderBoleto)
                .addGap(154, 154, 154)
                .addComponent(jBFunciones))
            .addGroup(jPMenuPrincipalLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jBCancelarBoleto)
                .addGap(116, 116, 116)
                .addComponent(jBCrearFuncion))
            .addGroup(jPMenuPrincipalLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jBCancelarFuncion))
        );
        jPMenuPrincipalLayout.setVerticalGroup(
            jPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuPrincipalLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBVenderBoleto)
                    .addComponent(jBFunciones))
                .addGap(40, 40, 40)
                .addGroup(jPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelarBoleto)
                    .addComponent(jBCrearFuncion))
                .addGap(31, 31, 31)
                .addComponent(jBCancelarFuncion))
        );

        getContentPane().add(jPMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 610, 590));

        jPFunciones.setVisible(false);
        jPFunciones.setPreferredSize(new java.awt.Dimension(610, 670));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jBFunciones, org.jdesktop.beansbinding.ELProperty.create("${action}"), jPFunciones, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("jTextField1");

        jLabel1.setText("Funcion");

        jButton1.setText("Asientos Disponibles");

        jBAtrasFunciones_Main.setText("Atras");

        jLabel7.setText("Lista de Funciones");

        javax.swing.GroupLayout jPFuncionesLayout = new javax.swing.GroupLayout(jPFunciones);
        jPFunciones.setLayout(jPFuncionesLayout);
        jPFuncionesLayout.setHorizontalGroup(
            jPFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionesLayout.createSequentialGroup()
                .addGroup(jPFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFuncionesLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(112, 112, 112)
                        .addGroup(jPFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPFuncionesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAtrasFunciones_Main)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 127, Short.MAX_VALUE))
            .addGroup(jPFuncionesLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFuncionesLayout.setVerticalGroup(
            jPFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBAtrasFunciones_Main)
                .addGap(108, 108, 108)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(161, 161, 161))
        );

        getContentPane().add(jPFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 620, 630));

        jPCancelarBoletos.setVisible(false);
        jPCancelarBoletos.setMaximumSize(new java.awt.Dimension(610, 670));
        jPCancelarBoletos.setPreferredSize(new java.awt.Dimension(610, 670));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jBCancelarBoleto, org.jdesktop.beansbinding.ELProperty.create("${action}"), jPCancelarBoletos, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jBAtrasCancelarB_Main.setText("Atras");

        jLabel8.setText("Función del Boleto");

        jLabel9.setText("Numero de Asiento");

        jBCancelarBoletoAsiento.setText("Cancelar Boleto");

        javax.swing.GroupLayout jPCancelarBoletosLayout = new javax.swing.GroupLayout(jPCancelarBoletos);
        jPCancelarBoletos.setLayout(jPCancelarBoletosLayout);
        jPCancelarBoletosLayout.setHorizontalGroup(
            jPCancelarBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCancelarBoletosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPCancelarBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCancelarBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jBAtrasCancelarB_Main))
                    .addComponent(jLabel9))
                .addGap(98, 98, 98)
                .addGroup(jPCancelarBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelarBoletoAsiento)
                    .addGroup(jPCancelarBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField5)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPCancelarBoletosLayout.setVerticalGroup(
            jPCancelarBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCancelarBoletosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jBAtrasCancelarB_Main)
                .addGap(45, 45, 45)
                .addGroup(jPCancelarBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCancelarBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jBCancelarBoletoAsiento)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        getContentPane().add(jPCancelarBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 610, 640));

        jPCrearFuncion.setVisible(false);
        jPCrearFuncion.setMaximumSize(new java.awt.Dimension(610, 670));
        jPCrearFuncion.setPreferredSize(new java.awt.Dimension(610, 670));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jBCrearFuncion, org.jdesktop.beansbinding.ELProperty.create("${action}"), jPCrearFuncion, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jBCrearFuncion_Main.setText("Atras");

        jLabel10.setText("Nombre de la Funcion");

        jLabel11.setText("Horario de la Funcion");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jBAneadirFuncion.setText("Crear Funcion");

        javax.swing.GroupLayout jPCrearFuncionLayout = new javax.swing.GroupLayout(jPCrearFuncion);
        jPCrearFuncion.setLayout(jPCrearFuncionLayout);
        jPCrearFuncionLayout.setHorizontalGroup(
            jPCrearFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCrearFuncionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPCrearFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(jPCrearFuncionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jBCrearFuncion_Main)))
                .addGap(130, 130, 130)
                .addGroup(jPCrearFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAneadirFuncion)
                    .addGroup(jPCrearFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField7)
                        .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPCrearFuncionLayout.setVerticalGroup(
            jPCrearFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCrearFuncionLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jBCrearFuncion_Main)
                .addGap(61, 61, 61)
                .addGroup(jPCrearFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPCrearFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jBAneadirFuncion)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        getContentPane().add(jPCrearFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 610, 670));

        jBAsientosDisponibles.setVisible(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jBSeleccionarAsientosDeCompra, org.jdesktop.beansbinding.ELProperty.create("${action}"), jBAsientosDisponibles, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jBAsientosDisponiblesLayout = new javax.swing.GroupLayout(jBAsientosDisponibles);
        jBAsientosDisponibles.setLayout(jBAsientosDisponiblesLayout);
        jBAsientosDisponiblesLayout.setHorizontalGroup(
            jBAsientosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jBAsientosDisponiblesLayout.setVerticalGroup(
            jBAsientosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(jBAsientosDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 610, 640));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearFuncionActionPerformed
        // TODO add your handling code here:
         jPMenuPrincipal.setVisible(false);
         jPCrearFuncion.setVisible(true);
    }//GEN-LAST:event_jBCrearFuncionActionPerformed

    private void jBVenderBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVenderBoletoActionPerformed
        // TODO add your handling code here:

        jPMenuPrincipal.setVisible(false);
        jPVentaBoletos.setVisible(true);
    }//GEN-LAST:event_jBVenderBoletoActionPerformed

    private void jBCancelarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarBoletoActionPerformed
        // TODO add your handling code here:
        
        jPMenuPrincipal.setVisible(false);
        jPCancelarBoletos.setVisible(true);
    }//GEN-LAST:event_jBCancelarBoletoActionPerformed

    private void jBFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFuncionesActionPerformed
        // TODO add your handling code here:
         jPMenuPrincipal.setVisible(false);
         jPFunciones.setVisible(true);
    }//GEN-LAST:event_jBFuncionesActionPerformed

    private void jBCancelarFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarFuncionActionPerformed
        // TODO add your handling code here:
         jPMenuPrincipal.setVisible(false);
         jPCancelarFuncion.setVisible(true);
    }//GEN-LAST:event_jBCancelarFuncionActionPerformed

    private void jBCancelarFuncionSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarFuncionSeleccionadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarFuncionSeleccionadaActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAneadirFuncion;
    private javax.swing.JPanel jBAsientosDisponibles;
    private javax.swing.JButton jBAtrasBoletos_Main;
    private javax.swing.JButton jBAtrasCancelarB_Main;
    private javax.swing.JButton jBAtrasCancelarF_Main;
    private javax.swing.JButton jBAtrasFunciones_Main;
    private javax.swing.JButton jBCancelarBoleto;
    private javax.swing.JButton jBCancelarBoletoAsiento;
    private javax.swing.JButton jBCancelarFuncion;
    private javax.swing.JButton jBCancelarFuncionSeleccionada;
    private javax.swing.JButton jBComprarBoletos;
    private javax.swing.JButton jBCrearFuncion;
    private javax.swing.JButton jBCrearFuncion_Main;
    private javax.swing.JButton jBFunciones;
    private javax.swing.JButton jBSeleccionarAsientosDeCompra;
    private javax.swing.JButton jBVenderBoleto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCancelarBoletos;
    private javax.swing.JPanel jPCancelarFuncion;
    private javax.swing.JPanel jPCrearFuncion;
    private javax.swing.JPanel jPFunciones;
    private javax.swing.JPanel jPMenuPrincipal;
    private javax.swing.JPanel jPVentaBoletos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
